### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by piaohualouzhu** [widevineleak/Chrome-Widevine-Guesser-2023#2]
![123](https://github.com/widevineleak/Chrome-Widevine-Guesser-2023/assets/70653444/9d232466-ad36-479d-839c-f119d05b4257)

**Comment by whip28** [comment]
same problem

**Comment by widevineleak** [comment]
we are updating it soon it will be up

**Comment by widevineleak** [comment]
new launched
